name: Sync bot on CSML Studio

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  csml-studio-sync:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync with studio
        uses: cvere/csml-studio-sync-action@vcvr
  
        with:
          update: true
          build: true
        env:
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
          DEBUG: "true"

      - name: Create new snapshot
        uses: CSML-by-Clevy/csml-studio-sync-action@v1.0-beta7
        with:
          create-snapshot: true
        env:
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
          DEBUG: "true"
